from enum import Enum


class ChartType(str, Enum):
    BAR = "bar"
    LINE = "line"
    SCATTER = "scatter"
    PIE = "pie"
    HISTOGRAM = "histogram"
    HEATMAP = "heatmap"
    BOX = "box"
    VIOLIN = "violin"
    STRIP = "strip"
    FUNNEL = "funnel"
    FUNNEL_AREA = "funnel_area"
    TREEMAP = "treemap"
    SUNBURST = "sunburst"
    ICICLE = "icicle"
    WATERFALL = "waterfall"
    AREA = "area"
    RADAR = "radar"
    DENSITY_HEATMAP = "density_heatmap"
    DENSITY_CONTOUR = "density_contour"
    SCATTER_GEOMAP = "scatter_geo"
    CHOROPLETH = "choropleth"
    SCATTER_MATRIX = "scatter_matrix"
    PARALLEL_COORDINATES = "parallel_coordinates"
    PARALLEL_CATEGORIES = "parallel_categories"
    SCATTER_3D = "scatter_3d"
    GAUGE = "gauge"
    TIMELINE = "timeline"
